In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None) # Show all columns
import torch

#### Numpy Basics

In [12]:
### 1D numpy Arrays

a = np.array([1, 2, 3,4,5])
b = np.array([6,7,8,9,10])

print(a+b)
print(a-b)
print(3*a)


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 3  6  9 12 15]


In [13]:
print(np.dot(a,b))

130


In [14]:
print(a@b)

130


In [15]:
### 2D numpy Arrays

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

In [16]:
print(A + B) 
print(A - B)
print(2 * A)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 2  4  6]
 [ 8 10 12]]


In [17]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [20]:
B = np.array([[7, 8, 9], [10, 11, 12]])
X = np.array([[1, 2, 3, 8], [4, 5, 6, 7], [8, 3, 1, 9]])

print(B@X)
print(np.dot(B,X))

[[111  81  78 193]
 [150 111 108 265]]
[[111  81  78 193]
 [150 111 108 265]]




@ Operator: This is the modern, recommended way to do matrix multiplication in Python.

np.dot() Function: This is a more general-purpose function.

When given two 2D arrays, it performs matrix multiplication.

When given two 1D arrays (vectors), it computes their dot product.

Its behavior changes based on the dimensions of the input arrays.

For 2D arrays, @ and np.dot() are functionally identical. The @ operator is often preferred because its meaning is unambiguous and it can make code more readable.

In [18]:
###  Numpy Broadcasting

X = np.array([[1, 2, 3, 8], [4, 5, 6, 7], [8, 3, 1, 9]])
Y = np.array([[2], [3], [4]])

print(X + Y)

[[ 3  4  5 10]
 [ 7  8  9 10]
 [12  7  5 13]]


Numpy Broadcasting explained

The smaller array Y was stretched to match the shape of the larger array X and then the 2 arrays were added element wise.
NumPy automatically expanded Y to a shape of 3 rows and 4 columns by duplicating its single column three more times.

Internal working of Numpy Broadcasting
[[1, 2, 3, 8],      [[2, 2, 2, 2],      [[1+2, 2+2, 3+2, 8+2],      [[ 3,  4,  5, 10],
 [4, 5, 6, 7],   +   [3, 3, 3, 3],   =   [4+3, 5+3, 6+3, 7+3],   =   [ 7,  8,  9, 10],
 [8, 3, 1, 9]]       [4, 4, 4, 4]]       [8+4, 3+4, 1+4, 9+4]]       [12,  7,  5, 13]]

This automatic expansion is a core feature of NumPy called broadcasting. It allows for efficient computations between arrays of different, but compatible, shapes without needing to create extra copies of the data in memory.

In [19]:
# Our 1D array of length 4 (acts like a 1x4 row vector)
row_vector = np.array([10, 20, 30, 40])

print(X + row_vector)

[[11 22 33 48]
 [14 25 36 47]
 [18 23 31 49]]


When we add a 1D array (which NumPy treats as a row vector in this context) to a 2D array (a matrix), broadcasting rules are applicable to make the shapes compatible for element-wise addition.

Shape Comparison:

X has a shape of (3, 4).

row_vector has a shape of (4,).

Applying the Broadcasting Rules:

Rule 1: To compare the shapes, NumPy first aligns their dimensions from the right. To make them have the same number of dimensions, it pads the shape of the smaller array (row_vector) with a 1 on the left. So, (4,) is treated as (1, 4).

Rule 2: Now NumPy compares the shapes (3, 4) and (1, 4) dimension by dimension.

Columns (trailing dimension): Both have a size of 4. This is a match.

Rows (first dimension): X has 3 rows, while the row_vector has 1. Since one of the dimensions is 1, NumPy "stretches" or duplicates the row_vector along this axis to match the other array's size.

In [21]:
# Create a 100x100x3 array representing an RGB image.
# Fill it with random integers from 0 to 255 to simulate pixel data.
image_data = np.random.randint(0, 256, size=(100, 100, 3), dtype=np.uint8)

# Create a 1D array to scale the color channels (Red, Green, Blue).
# For example, we'll reduce red, increase green, and slightly reduce blue.
color_scale = np.array([0.5, 1.2, 0.8])

# Multiply the image by the color scale using broadcasting.
# Note: The result will be float numbers.
scaled_image_data = image_data * color_scale

print("Shape of original image_data:", image_data.shape)
print("Shape of color_scale:", color_scale.shape)
print("Shape of scaled_image_data:", scaled_image_data.shape)

# Let's check the values for the first pixel before and after scaling
print("\nOriginal first pixel (R,G,B):", image_data[0, 0, :])
print("Scaled first pixel (R,G,B):", scaled_image_data[0, 0, :])


Shape of original image_data: (100, 100, 3)
Shape of color_scale: (3,)
Shape of scaled_image_data: (100, 100, 3)

Original first pixel (R,G,B): [ 83 229  41]
Scaled first pixel (R,G,B): [ 41.5 274.8  32.8]
