In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None) # Show all columns
import torch

#### Coding Challenge 1 (Dot Products & Matrix-Vector)

In [2]:
### 1D array vector

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a@b)
print(np.dot(a,b))


32
32


In [3]:
### 2D array matrix

M = np.array([[1,2], [4,5], [7,8]])
v = np.array([10,5])

print(M@v)

print(np.dot(M,v))

[ 20  65 110]
[ 20  65 110]


#### Coding Challenge 2 (Matrix-Matrix)

In [4]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8, 6, 3], [9,10,5,2], [11,12,13,14]])

print(A@B)
print(np.dot(A,B))

[[ 58  64  55  49]
 [139 154 127 106]]
[[ 58  64  55  49]
 [139 154 127 106]]


In [5]:
print(A)
print(B)


[[1 2 3]
 [4 5 6]]
[[ 7  8  6  3]
 [ 9 10  5  2]
 [11 12 13 14]]


In [7]:
C = A@B
C[0,0]

58

In [8]:
C[1,2]

127

In [9]:
C[0,1]

64

#### Coding Challenge 3 (Linear Transformation Simulation - Conceptual)

In [2]:
# --- Challenge 3: Linear Transformation Simulation (Conceptual) ---
# Objective: Understand how a matrix multiplication transforms a vector.

# 1. Define a simple 2x2 transformation matrix 'T'.
# Let's pick one that's easy to visualize, e.g., a scaling matrix.
# This matrix scales the x-component by 2 and the y-component by 0.5.
T = np.array([[2, 0],
              [0, 0.5]])

print(f"\nTransformation Matrix T:\n{T}")

# 2. Define a simple 2D vector 'v'.
v = np.array([1, 1])
print(f"\nOriginal Vector v: {v}")

# 3. Calculate the transformed vector 'v_transformed'.
v_transformed = T @ v
print(f"Transformed Vector v': {v_transformed}")




Transformation Matrix T:
[[2.  0. ]
 [0.  0.5]]

Original Vector v: [1 1]
Transformed Vector v': [2.  0.5]


--- Self-Reflection and Conceptual Explanation (Add these comments to your notebook) ---

Question 1: How did 'v' change after being multiplied by 'T'?

Answer:

The original vector v=[1, 1] was transformed to v'=[2, 0.5].
This means its x-component was scaled by a factor of 2, and its y-component was scaled by a factor of 0.5.
This aligns with the scaling factors on the diagonal of matrix T.

Question 2: If 'v' represented a point (1,1) in a 2D plane, what would 'T' do to a set of points forming a unit square (0,0), (1,0), (0,1), (1,1)?

Conceptual Answer (no code needed for this):
- The point (0,0) would remain (0,0) (as T @ [0,0] = [0,0]).
- The point (1,0) would become (2,0) (scaled along x-axis).
- The point (0,1) would become (0,0.5) (scaled along y-axis).
- The point (1,1) (our 'v') would become (2,0.5).
So, the unit square would be "stretched" along the x-axis and "compressed" along the y-axis,
forming a rectangle with corners at (0,0), (2,0), (0,0.5), (2,0.5).
This demonstrates how matrices perform linear transformations (scaling, rotation, shearing, etc.) on space.

Question 3: How is this relevant to neural networks?

Answer:

In a neural network's dense (fully connected) layer, the input vector (X) is multiplied by a weight matrix (W).
This multiplication (X @ W, or W @ X depending on conventions) is essentially a linear transformation of the input data.
Each neuron in the next layer is taking a transformed combination of the inputs from the previous layer.
This transformation is the "linear part" of learning, before non-linear activation functions are applied.